### PR TITLE
Redirections are handled by Symfony / removed handlers

### PR DESCRIPTION
**Pull request by romaricdrigon**
Hi,

This PR is a partial refactor, ditching the custom handlers in favor of the ones provided by Symfony2:

 * the *login success* and *logout success* handlers have been removed
 * the *login failure* handler have been modified to extend the Synfony provided one, not to handle the redirection anymore
 * the *route referer listener* is not required anymore, so it has been removed

This approach reduces the code while allowing more flexibility: in our application, we have several login routes, which is appropriately handled by Symfony default handlers, but not anymore when using this bundle and its single `login_route`.

Configuration has been simplified: we don't need anymore to specify `login.success_handler`, `logout_success_handler` or all the `route_referer` block. Those have been removed from the installation instructions.

Backward-compatibility is full: services aliases has been added and the `route_referer` configuration key is still valid. Though later (3.0 ?) this legacy-compatibility layer could be removed.

This PR will conflict with #44 and #43, as those are not relevant anymore.

### CODE REVIEW

**Comment by reecefowell** [comment]
After merging your other PR's this one will need rebasing before I can merge it.

**Comment by romaricdrigon** [comment]
Sure, I'm working on that right now!

**Comment by romaricdrigon** [comment]
Done!

**Comment by reecefowell** [comment]
Thanks :)

**Comment by romaricdrigon** [comment]
My pleasure, first of all thanks for that pretty useful bundle!

**Pull request merged**
